name: Build and Publish Docker Image
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: gustun-test-1
        service_account_key: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true
    
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet

    - name: Build and push the docker image
      run: |
        docker build -t gcr.io/gustun-test-1/house-whisperer:${{ github.sha }} .
        docker push gcr.io/gustun-test-1/house-whisperer:${{ github.sha }}
